version: '3.3'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - "8098:80"
    links:
      - fpm
    volumes:
        - ~/Junior/blog:/var/www/html
        - ./nginx_conf:/etc/nginx/sites-enabled/
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes:
      - ./:/var/www
    links:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: blog-db
    restart: always
    env_file:
        - .env
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
